<?php

/**
 * @file
 * Contains metatag_google_scholar.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function metatag_google_scholar_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the metatag_google_scholar module.
    case 'help.page.metatag_google_scholar':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Google Scholar tags') . '</p>';
      return $output;

    default:
  }
}
