commerce_payment.commerce_payment_gateway.plugin.paypal_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    secret:
      type: string
      label: 'Secret'
    intent:
      type: string
      label: 'Intent'
    disable_funding:
      type: sequence
      label: 'Disable funding sources'
      sequence:
        type: string
    disable_card:
      type: sequence
      label: 'Disable card types'
      sequence:
        type: string
    shipping_preference:
      type: string
      label: 'Shipping preference'
    update_billing_profile:
      type: boolean
      label: 'Update billing profile'
    update_shipping_profile:
      type: boolean
      label: 'Update shipping profile'
    style:
      type: mapping
      label: 'Style'
      mapping:
        layout:
          type: string
          label: 'Layout'
        color:
          type: string
          label: 'Color'
        shape:
          type: string
          label: 'Shape'
        label:
          type: string
          label: 'Label'
        tagline:
          type: boolean
          label: 'Display tagline'
commerce_payment.commerce_payment_gateway.plugin.paypal_express_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    api_username:
      type: string
      label: 'API Username'
    api_password:
      type: string
      label: 'API Password'
    shipping_prompt:
      type: string
      label: 'Shipping address collection'
    signature:
      type: string
      label: 'Signature'
    solution_type:
      type: string
      label: 'Type of checkout flow'
commerce_payment.commerce_payment_gateway.plugin.paypal_payflow:
  type: commerce_payment_gateway_configuration
  mapping:
    partner:
      type: string
      label: 'Partner'
    vendor:
      type: string
      label: 'Vendor'
    user:
      type: string
      label: 'User'
    password:
      type: string
      label: 'Password'
