<?php

/**
 * @file
 * Newsletter signup.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_mail().
 */
function newslettersignup_mail($key, &$message, $params) {
  switch ($key) {
    case 'signup_notify':
      $message['from'] = \Drupal::config('system.site')->get('mail');

      $message['subject'] = t('Newsletter Signup');

      $message_body['name'] = $params['message']['newsletteryourname'];
      $message_body['company_name'] = $params['message']['newslettercompanyname'];
      $message_body['email'] = $params['message']['newsletteryouremail'];
      
      /**
       * Assign a twig template for message body
       */
      $message_theme_body = array(
        '#theme' => 'newslettersignup_notify_email',
        '#message_body' => $message_body,
       );
      
      $message_render = \Drupal::service('renderer')->render($message_theme_body);
      $message['body'][] = Html::escape($message_render);
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed;';
      break;
  }
}

/**
 * Implements hook_theme().
 */
function newslettersignup_theme($existing, $type, $theme, $path) {
  return [
    'newslettersignup_notify_email' => [
      'variables' => ['message_body' => NULL],
    ],
  ];
}
