metatag.metatag_tag.citation_title:
  type: label
  label: 'Title'
metatag.metatag_tag.citation_author:
  type: label
  label: 'Author'
metatag.metatag_tag.citation_publication_date:
  type: label
  label: 'Publication date'
metatag.metatag_tag.citation_journal_title:
  type: label
  label: 'Journal title'
metatag.metatag_tag.citation_issn:
  type: label
  label: 'ISSN'
metatag.metatag_tag.citation_isbn:
  type: label
  label: 'ISBN'
metatag.metatag_tag.citation_volume:
  type: label
  label: 'Volume'
metatag.metatag_tag.citation_issue:
  type: label
  label: 'Issue'
metatag.metatag_tag.citation_firstpage:
  type: label
  label: 'First page'
metatag.metatag_tag.citation_lastpage:
  type: label
  label: 'Last page'
metatag.metatag_tag.citation_dissertation_institution:
  type: label
  label: 'Dissertation institution'
metatag.metatag_tag.citation_technical_report_institution:
  type: label
  label: 'Technical report institution'
metatag.metatag_tag.citation_technical_report_number:
  type: label
  label: 'Technical report number'
metatag.metatag_tag.citation_pdf_url:
  type: label
  label: 'PDF URL'
